---
title: "WLE Heatmaps"
author: "Maurício Collaça"
date: "December 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data validation and transformation
```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr); library(RColorBrewer)
training <- read.csv("pml-training.csv", na.strings=c("NA","","#DIV/0!"))
testing <- read.csv("pml-testing.csv", na.strings=c("NA","","#DIV/0!"))
source("HAR-WLE-utils.R"); WLEdataCleanup()
```
```{r include=FALSE}
blue.pal <- function(n) { f <- colorRampPalette(brewer.pal(9, "Blues")) ; rev(f(n)) }
grey.pal <- function(n) { f <- colorRampPalette(brewer.pal(9, "Greys")) ; rev(f(n)) }
heat.pal <- function(n) { f <- colorRampPalette(brewer.pal(9, "YlOrRd")) ; rev(f(n)) }
```
```{r include=FALSE}
imagemap <- function(x, scale, cluster, col, main, cex.axis=1) {
    if(cluster) {
        distance <- dist(x)
        distanceT <- dist(t(x))
        rowInd <- order.dendrogram(reorder(as.dendrogram(hclust(distance)), rowMeans(x)))
        colInd <- order.dendrogram(reorder(as.dendrogram(hclust(distanceT)), colMeans(x)))
        if(scale) {
            x<-scale(x)
        }
        image(t(x[rowInd, colInd]), col=col, axes=FALSE, main=main)
    }
    else {
        if(scale) {
            x<-scale(x)
        }
        image(t(x), col=col, axes=FALSE, main=main)
    }
    axis(1, at=seq(0,1, length=ncol(x)), labels = colnames(x), las=2, cex.axis=cex.axis, hadj=0.9, padj=0)
}
```

```{r classeUserClusters, echo=FALSE, fig.height=10, fig.width=20, cache=TRUE}
dataColors <- heat.pal(4)
par(mfrow=c(1,2), mar=c(9,1,2,1))
m <- scale(as.matrix(training[, -c(1:4,57)])) # scales before order
imagemap(m[order(training$classe, training$user_name),],
         scale=FALSE, cluster=FALSE, col = dataColors,
         main="Rows ordered by classe and user", cex.axis=1)
ys <- cumsum(table(training$classe))/sum(table(training$classe))
abline(h=ys, lty=1, lwd=1)
text(x=0, y=ys, labels=levels(training$class), adj=c(0,1), cex=1)
imagemap(m[order(training$user_name, training$classe), ],
         scale=FALSE, cluster=FALSE, col = dataColors,
         main="Rows ordered by user and classe", cex.axis=1)
ys <- cumsum(table(training$user_name))/sum(table(training$user_name))
abline(h=ys, lty=1, lwd=1)
text(x=0, y=ys, labels=levels(training$user_name), adj=c(0,1), cex=1)
```

```{r overallCluster, echo=FALSE, fig.height=10, fig.width=10, cache=TRUE}
m <- as.matrix(training[, -c(1:4,57)])
dataColors <- heat.pal(12)
rowColors <- grey.pal(nrow(m)); colColors <- grey.pal(ncol(m))
heatmap(m, scale="column", margins=c(10,1), cexCol=1, RowSideColors=rowColors, ColSideColors=colColors,
        col=dataColors,
        labRow=NA, main="Rows and columns ordered by cluster dendrograms")
```

**Heatmaps segmented by user with rows and columns ordered by hierarchical cluster**

```{r userCluster, echo=FALSE, fig.height=20, fig.width=20, cache=TRUE}
dataColors <- heat.pal(8)
par(mfrow=c(2,3), mar=c(9,1,2,1))
m <- scale(as.matrix(training[, -c(1:4,57)]))
for (user in levels(training$user_name)) {
    imagemap(m[training$user_name==user, ], scale=FALSE, cluster=TRUE, col = dataColors, main=user, cex.axis=1)
}
```

**Heatmaps segmented by sensor set with rows and columns ordered by hierarchical cluster**
```{r sensorClusters, echo=FALSE, fig.height=10, fig.width=20, cache=TRUE}
dataColors <- heat.pal(20)
par(mfrow=c(1,4), mar=c(9,1,2,1))
m <- scale(as.matrix(training[, -c(1:4,57)])) # scales before subsetting
for(sensor in c("arm","belt","dumbbell","forearm")) {
    imagemap(m[,grep(paste0("_",sensor), names(training), value=TRUE)],
             scale=FALSE, cluster=TRUE, col=dataColors, main=sensor, cex.axis=1)
}
```

**Heatmaps segmented by classe with rows and columns ordered by hierarchical cluster**
```{r classeClusters, echo=FALSE, fig.height=20, fig.width=20, cache=TRUE}
dataColors <- heat.pal(6)
par(mfrow=c(2,3), mar=c(9,1,2,1))
m <- scale(as.matrix(training[, -c(1:4,57)])) # scales before subsetting
for(classe in levels(training$classe)) {
    imagemap(m[training$classe==classe, ],
             scale=FALSE, cluster=TRUE, col=dataColors, main=classe, cex.axis=1)
}
```
