---
title: "WLE Scatterplots"
author: "Maurício Collaça"
date: "December 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr); library(tidyr); library(ggplot2);
training <- read.csv("pml-training.csv", na.strings=c("NA","","#DIV/0!"))
testing <- read.csv("pml-testing.csv", na.strings=c("NA","","#DIV/0!"))
source("HAR-WLE-utils.R"); WLEdataCleanup()
```
```{r include=FALSE}
prepareFacet <- function(data, groups, features, color, lhsName, lhsPattern, lhsReplacement, rhsName, rhsPattern, rhsReplacement) {
    data %>%
        select(matches(groups), matches(features), matches(color)) %>%
        mutate_at(vars(matches(groups)), factor) %>%
        mutate_at(vars(matches(color)), factor) %>%
        gather(key="feature", value = "value", -matches(groups), -matches(color), factor_key = TRUE) %>%
        mutate(!!lhsName := factor(sub(lhsPattern, lhsReplacement, feature)),
               !!rhsName := factor(sub(rhsPattern, rhsReplacement, feature)),
               feature = NULL) %>%
        group_by_at(vars(matches(groups), lhsName, rhsName)) %>% mutate(index=row_number()) %>% ungroup() %>%
        select(matches(groups), lhsName, rhsName, value, index, matches(color))
}
```
#### All features faceted on sensor set and users
```{r allFeatures, echo=FALSE, fig.height=60, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "(_arm|_belt|_dumbbell|_forearm)",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of all features faceted on sensor set and users") +
    facet_grid(sensor_set + user_name ~ signal,
               margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```

#### Accelerometer features faceted on sensor set and users
```{r accelScatter, echo=FALSE, fig.height=60, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "^accel",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of Accelerometer features faceted on sensor set and users") +
    facet_grid(sensor_set + user_name ~ signal,
               margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```

#### Magnetometer features faceted on sensor set and users
```{r magnetScatter, echo=FALSE, fig.height=60, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "^magnet.+[xyz]$",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of magnetometer features faceted on sensor set and users") +
    facet_grid(sensor_set + user_name ~ signal,
               margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```

#### Total accelerometer faceted on users and sensor set
```{r totalAccelScatter, echo=FALSE, fig.height=10, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "^total_accel",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of total accelerometer faceted on users and sensor set") +
    facet_grid(user_name ~ signal + sensor_set,
               margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```

#### Gyroscope features faceted on sensor set and users
```{r gyrosScatter, echo=FALSE, fig.height=60, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "^gyros.+[xyz]$",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of gyroscope features faceted on sensor set and users") +
    facet_grid(sensor_set + user_name ~ signal,
               margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```

#### Euler angle features faceted on sensor set and users
```{r eulerAngleScatter, echo=FALSE, fig.height=60, fig.width=20, cache=TRUE}
data <- prepareFacet(data = training,
                     groups = "user_name",
                     color = "classe",
                     features = "^(pitch|roll|yaw)_(arm|belt|dumbbell|forearm)$",
                     lhsName = "sensor_set",
                     lhsPattern = "^.+_(arm|belt|dumbbell|forearm)_?.*$",
                     lhsReplacement = "\\1",
                     rhsName = "signal",
                     rhsPattern = "^(.+)_(arm|belt|dumbbell|forearm)(_?)(.*)$",
                     rhsReplacement = "\\1\\3\\4")
ggplot(data, aes(x=index, y=value, color=classe)) + theme_bw() + theme(legend.position = "top") +
    ggtitle("Scatter plots of Euler angle features faceted on sensor set and users") +
    facet_grid(sensor_set + user_name ~ signal,
              margins=FALSE, scales="free", space="free", shrink=TRUE, switch="y") +
    geom_point() + geom_smooth(method="loess", color=1, se = FALSE) +
    geom_smooth(method="lm", color=1, linetype=2, se = FALSE)
```
