---
title: 'HAR WLE Feature recreation'
author: "Maurício Collaça"
date: "December 5, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document analyzes the "#DIV/0!" issue found in many features (statistics) of HAR WLE dataset and aims to reproduce the feature creation process.

## Data loading
```{r message=FALSE, warning=FALSE}
library(dplyr)
training <- read.csv("pml-training.csv", stringsAsFactors = FALSE)
testing <- read.csv("pml-testing.csv", stringsAsFactors = FALSE)
```

## Training Variables containing "#DIV/0!"

```{r}
(DIV0Cols <- names(which(colSums(sapply(training, function(x) is.character(x) & x=="#DIV/0!")) > 0)))
```

### Selecting the first case
```{r}
training %>% filter_all(any_vars(. == "#DIV/0!")) %>%
    select(1:7, one_of(DIV0Cols)) %>%
    head(1)
```

### Selecting the first 10 new windows from the first case and features of pitch_belt
```{r}
training %>%
    filter(user_name=="carlitos" & new_window=="yes") %>%
    select(2:3, ends_with("_pitch_belt"), ends_with("_picth_belt")) %>% slice(1:10) %>% knitr::kable()
```

### TODO: Trying to reproduce the first 10 new windows
```{r}
#TODO: get the window logic in the documentation
training %>%
    filter(user_name=="carlitos") %>%
    group_by(user_name, raw_timestamp_part_1) %>%
    summarise(min_pitch_belt = min(pitch_belt), amplitude_pitch_belt = max(pitch_belt) - min(pitch_belt),
              avg_pitch_belt = mean(pitch_belt),stddev_pitch_belt = sd(pitch_belt), var_pitch_belt = var(pitch_belt),
              kurtosis_pitch_belt = e1071::kurtosis(pitch_belt), max_pitch_belt = max(pitch_belt)) %>% slice(1:10) %>% knitr::kable()
```

